apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-1re4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-1re4
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-1re4
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-1re4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-1re4
    spec:
      containers:
      - image: quay.io/qijing/push-pyxis-xhsd-tenant/appstudio/dc-metro-map-1re4@sha256:6b70e8e1cb3ce3493c941f23bba7f62277237957907b05347c5a7b42153b4e90
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
